### ISSUE TITLE
Initial render looks to be not working

### ISSUE THREAD

**Issue by rolivegab** [ayrtoneverton/react-hooks-simple-global-state#1]
After second click, it works normally, see small reproduction example:
https://codesandbox.io/s/small-test-ayrton-2384m5?file=/src/App.tsx

Either way, very nice library, indeed is very simple to use. :+1:

**Comment by ayrtoneverton** [comment]
First, thank you very much for contributing, @rolivegab :)

I think we got off to a great start 🥳, as the problem was very specific to StrictMode in React 18, so thanks a lot for the test and the feedback 👏👏👏

The issue has been resolved in version `1.0.2`. 🚀
